print("# Fahrenheit to Celsius conversion program")
print("")
print("fahren = float(input('Enter degrees Fahrenheit: '))")
print("celsius = (fahren - 32) * 5 / 9")
print("print(fahren, 'degrees Fahrenheit equals',")
print("      format(celsius, '.1f'), 'degrees Celsius')")